{
  try {
    while (true) {
      Exception e=null;
      try {
        if (fn == null) {
          LOG.warn("fn==null");
          throw new RuntimeException("AsyncLoopRunnable no core function ");
        }
        fn.run();
        e=fn.error();
      }
 catch (      Exception ex) {
        e=ex;
      }
      if (e != null) {
        fn.shutdown();
        throw e;
      }
      Object rtn=fn.getResult();
      if (this.needQuit(rtn)) {
        return;
      }
    }
  }
 catch (  InterruptedException e) {
    LOG.info("Async loop interrupted!");
  }
catch (  Throwable e) {
    Object rtn=fn.getResult();
    if (this.needQuit(rtn)) {
      return;
    }
 else {
      LOG.error("Async loop died!",e);
      killfn.execute(e);
    }
  }
}
